name = "SR_with_LLM_Complexity"
uuid = "0121520d-e24a-44dd-8a28-a2181f5d9830"
authors = ["Liz Tan <eszt2@cam.ac.uk>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
DynamicExpressions = "a40a106e-89c9-4ca8-8020-a735e8728b6b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PromptingTools = "670122d1-24a8-4d70-bfce-740807c42192"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymbolicRegression = "8254be44-1295-4e6a-a16d-46603ac705cb"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BenchmarkTools = "1.6.3"
DynamicExpressions = "1"
JSON = "1.2.0"
JSON3 = "1.14.3"
PromptingTools = "0.83.0"
Reexport = "1"
SymbolicRegression = "1"
julia = "1.10"
